### ISSUE TITLE
Actual IR

### ISSUE THREAD

**Issue by Benjozork** [Benjozork/cyan#3]
Needs actual IR for both interpreter and JS codegen

Additionally, IR would enable :
* compile-time type checking
* compile-time optimization / lowering
* multiple backends

**Comment by tripulse** [comment]
> JS codegen

:weary:
i hate ur leng, if u gen js cud

**Comment by Benjozork** [comment]
We can call this fixed now

**Comment by tripulse** [comment]
'' occ beri g00d '-'
-
